/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.danielrub.standalonejavaweb;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author 2379961
 */
public class Splash extends javax.swing.JFrame {

    public JLabel getJlabelLoadingText() {
        return JlabelLoadingText;
    }

    public void setJlabelLoadingText(JLabel JlabelLoadingText) {
        this.JlabelLoadingText = JlabelLoadingText;
    }

    public JLabel getJlabelSplash() {
        return JlabelSplash;
    }

    public void setJlabelSplash(JLabel JlabelSplash) {
        this.JlabelSplash = JlabelSplash;
    }

    public JLabel getReserved() {
        return Reserved;
    }

    public void setReserved(JLabel Reserved) {
        this.Reserved = Reserved;
    }

    public JLabel getjLApplicationName() {
        return jLApplicationName;
    }

    public void setjLApplicationName(JLabel jLApplicationName) {
        this.jLApplicationName = jLApplicationName;
    }

    public JLabel getjLApplicationVersion() {
        return jLApplicationVersion;
    }

    public void setjLApplicationVersion(JLabel jLApplicationVersion) {
        this.jLApplicationVersion = jLApplicationVersion;
    }

    public JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }

    public void setjProgressBar1(JProgressBar jProgressBar1) {
        this.jProgressBar1 = jProgressBar1;
    }

    
    
    
    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLApplicationVersion = new javax.swing.JLabel();
        jLApplicationName = new javax.swing.JLabel();
        JlabelLoadingText = new javax.swing.JLabel();
        Reserved = new javax.swing.JLabel();
        JlabelSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 280));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 280));
        setResizable(false);
        getContentPane().setLayout(null);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(80, 170, 340, 17);

        jLApplicationVersion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLApplicationVersion.setForeground(new java.awt.Color(255, 255, 255));
        jLApplicationVersion.setText("Ver 1.0");
        getContentPane().add(jLApplicationVersion);
        jLApplicationVersion.setBounds(350, 120, 70, 15);

        jLApplicationName.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        jLApplicationName.setForeground(new java.awt.Color(255, 255, 255));
        jLApplicationName.setText("Splash Screen");
        getContentPane().add(jLApplicationName);
        jLApplicationName.setBounds(80, 100, 270, 40);

        JlabelLoadingText.setForeground(new java.awt.Color(255, 255, 255));
        JlabelLoadingText.setText("Copyright Standalone Java Web\nFeb 2019");
        getContentPane().add(JlabelLoadingText);
        JlabelLoadingText.setBounds(80, 190, 330, 20);

        Reserved.setForeground(new java.awt.Color(255, 255, 255));
        Reserved.setText("Loading components...");
        getContentPane().add(Reserved);
        Reserved.setBounds(80, 140, 230, 20);

        JlabelSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splash.jpg"))); // NOI18N
        JlabelSplash.setText("jLabel1");
        getContentPane().add(JlabelSplash);
        JlabelSplash.setBounds(0, -10, 510, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelLoadingText;
    private javax.swing.JLabel JlabelSplash;
    private javax.swing.JLabel Reserved;
    private javax.swing.JLabel jLApplicationName;
    private javax.swing.JLabel jLApplicationVersion;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
